#include "soh.h"

#include <sstream>

using AT = rls::ast::Type;

namespace rls::transpilers::soh {

namespace {

std::optional<std::string_view> builtinEnumCppType(std::string_view enumName) {
    if (enumName == "Item") return "RandomizerGet";
    if (enumName == "Enemy") return "RandomizerEnemy";
    if (enumName == "Distance") return "EnemyDistance";
    if (enumName == "Trick") return "RandomizerTrick";
    if (enumName == "Setting") return "RandomizerSettingKey";
    if (enumName == "Region") return "RandomizerRegion";
    if (enumName == "Check") return "RandomizerCheck";
    if (enumName == "Logic") return "LogicVal";
    if (enumName == "Scene") return "SceneID";
    if (enumName == "Dungeon") return "DungeonKey";
    if (enumName == "Area") return "RandomizerArea";
    if (enumName == "Trial") return "TrialKey";
    if (enumName == "WaterLevel") return "RandoWaterLevel";
    return std::nullopt;
}

template <typename T>
std::string enumNodeType(const rls::ast::Project& p, const T* node) {
    auto enumType = p.getEnumType(node);
    if (!enumType.has_value()) {
        return "unsupported_type";
    }

    if (auto builtinType = builtinEnumCppType(*enumType); builtinType.has_value()) {
        return std::string(*builtinType);
    }

    // User/extern enums currently map directly to their enum name.
    return std::string(*enumType);
}

} // namespace

template <typename T>
std::string nodeType(const rls::ast::Project& p, const T* node) {
    const auto type = p.getType(node);
    if (!type.has_value()) {
        return "missing_type";
    }

    switch (type.value()) {
        case AT::Bool: return "bool";
        case AT::Int: return "int";
        case AT::Callable: return "std::function<bool()>";
        case AT::Condition: return "std::function<bool()>";
        case AT::Item: return "RandomizerGet";
        case AT::Enemy: return "RandomizerEnemy";
        case AT::Distance: return "EnemyDistance";
        case AT::Trick: return "RandomizerTrick";
        case AT::Setting: return "RandomizerSettingKey";
        case AT::Region: return "RandomizerRegion";
        case AT::Check: return "RandomizerCheck";
        case AT::Logic: return "LogicVal";
        case AT::Scene: return "SceneID";
        case AT::Dungeon: return "DungeonKey";
        case AT::Area: return "RandomizerArea";
        case AT::Trial: return "TrialKey";
        case AT::WaterLevel: return "RandoWaterLevel";
        case AT::Enum: return enumNodeType(p, node);
        default: return "unsupported_type";
    }
}

std::string functionSignature(
	const SohTranspiler& transpiler,
	const rls::ast::Project& p,
	const rls::ast::DefineDecl* decl,
    const bool includeDefaults)
{
    std::ostringstream sig;
    sig << nodeType(p, decl->body.get()) << " " << decl->name.text << "(";
    for (int i = 0; i < decl->params.size(); i++) {
        const auto& param = decl->params[i];
        sig << "const " << nodeType(p, &param) << " " << param.name.text;
        if (includeDefaults && param.defaultValue != nullptr) {
			sig << " = " + transpiler.GenerateExpression(param.defaultValue);
        }
        if (i < decl->params.size() - 1) {
            sig << ", ";
        }
    }
    sig << ")";
    return sig.str();
}

void SohTranspiler::GenerateFunctionDefinitionsHeader(rls::OutputWriter& out) const {
    auto& header = out.open("functions.gen.h");
    header << "// Generated by RLS soh transpiler\n"
           << "#pragma once\n"
           << "\n"
           << "#include <functional>\n"
           << "#include \"soh/Enhancements/randomizer/location_access.h\"\n"
           << "#include \"soh/Enhancements/randomizer/entrance.h\"\n"
           << "#include \"rls_match.h\"\n"
           << "#include \"rls_host.h\"\n"
           << "\n";

    for (const auto& [name, decl] : project.DefineDecls) {
        header << functionSignature(*this, project, decl, true) << ";\n";
    }
}

void SohTranspiler::GenerateFunctionDefinitionsSource(rls::OutputWriter& out) const {
    auto& source = out.open("functions.gen.cpp");
    source << "// Generated by RLS soh transpiler\n"
           << "#include \"functions.gen.h\"\n"
           << "#include \"rls_match.h\"\n";


    for (const auto& [name, decl] : project.DefineDecls) {
        source << "\n";
        
        source << functionSignature(*this, project, decl, false) << " {\n";
		source << "    return " << GenerateExpression(decl->body) << ";\n";
        source << "}\n";
    }
}

}